### ISSUE TITLE
help me implement this in correct & proper way

### ISSUE THREAD

**Issue by Uniminin** [Kreyren/kreyren#46]
upstream: https://raw.githubusercontent.com/Uniminin/CeeMeeWee/master/free/logic-gates.c
downstream: https://discordapp.com/channels/481111107394732043/685968652360482835/758982391888347146

**Comment by Kreyren** [comment]
What is this supposed to be doing?

**Comment by Kreyren** [comment]
FWIW i woudn't use `input1`, `input2` as i find it confusing assuming that this is implementing logic gates that are processing booleans. Would use `x`, `y`.

**Comment by Kreyren** [comment]
![image](https://user-images.githubusercontent.com/11302521/94325372-61444080-ff9e-11ea-8c1a-ee6ad22e4775.png)

What are your intentions with this

**Comment by Kreyren** [comment]
![image](https://user-images.githubusercontent.com/11302521/94325399-74571080-ff9e-11ea-8aa7-c7bb1658a8b3.png)

This should also be documented better

**Comment by Kreyren** [comment]
I would also think that this would be a cleaner code for OR gate.

```c
int OR(int x, int z) {
	if ((x = 1 && y = 0) || (x = 0 && y = 1)) {
		return 0
	} else { return 1 ;}
}
```

**Comment by Kreyren** [comment]
and FWIW i would probably wrapped this in a one function that is using switch based on provided argument to return the expected logic.
