### ISSUE TITLE
Review Rmake

### ISSUE THREAD

**Issue by Uniminin** [Kreyren/kreyren#54]
* UPSTREAM: [Uniminin/RMake](https://github.com/Uniminin/RMake)
* File to review: [Uniminin/RMake/blob/main/Makefile](https://github.com/Uniminin/RMake/blob/main/Makefile)

**Comment by Kreyren** [comment]
The thing that i liked the most on rustlang is that there is no fucking CMake with a voodoo lang to control the build.. AND YOU DO THIS TO ME?!

**Comment by Uniminin** [comment]
oof

**Comment by Kreyren** [comment]
I like how your stupidity always makes me to self improve like being forced to read source code of cargo-make to calm myself~ <3
