### ISSUE TITLE
Ren Spams Krey.. Again

### ISSUE THREAD

**Issue by rendragon4** [Kreyren/kreyren#83]
I hate you too much to tolerate anything from you. This is unlikely to change on its own within the next 1 to 2 years.

**Comment by Kreyren** [comment]
nah u must have confused me with someone else mate, it ain't possible to hate me~

**Comment by Kreyren** [comment]
also staph turning me issue tracking in a weird telenovela-like series of a social platform -.-

**Comment by rendragon4** [comment]
What does “again” mean? This is the first issue I’ve opened, and you were the one who initiated this phenomenon. It’s just that you deleted the issue you opened towards me earlier today so that no one else can see.

But okay. I’ll withhold such contributions to your github repositories in the future. Apologies.
さよなら

**Comment by Kreyren** [comment]
sigh
